from os import listdir
from os.path import isfile, join, dirname, abspath

if not __name__ == "__main__":
    exit(1)

baseDir = abspath(join(dirname(__file__), '..'))

OutputDir = join(baseDir, 'Graphx')
baseSvgDir = join(baseDir, 'Graphx', 'svg')

mainSvgFNames = [f for f in listdir(baseSvgDir) if isfile(join(baseSvgDir, f)) and f.lower().endswith('.svg')]

mainSvgFNames.sort()

mainSvgFiles = {}

for svgFile in mainSvgFNames:
    svgFilePath = join(baseSvgDir, svgFile)
    with open(svgFilePath, 'r') as f:
        mainSvgFiles[svgFile] = f.read()

mainOutputPath = join(OutputDir, 'main_images.py')

with open(mainOutputPath, 'w', encoding='utf-8', newline='\n') as f:
    f.write("# This file is auto-generated by Tools/MainSvgImgs2PyFiles.py\n")
    f.write("# Do not edit this file directly!\n\n")
    f.write("mainImages = {\n")
    for fname, content in mainSvgFiles.items():
        f.write(f'    "{fname}": b"""{content}""",\n')
    f.write("}\n")
